ARG BASE_VERSION
FROM processmaker/pm4-base:${BASE_VERSION}

RUN npm config set cache /cache/npm --global
ENV COMPOSER_HOME=/cache/composer

COPY ./pm4-tools /code/pm4-tools
WORKDIR /code/pm4-tools
RUN composer install --no-interaction

WORKDIR /code
COPY build-files/cicd-build-run.sh .
COPY build-files/cicd-run-app.sh .
COPY build-files/cicd-run-phpunit.sh .
COPY packages-to-install.php .