FROM processmaker/pm4-base:2.0.0

RUN npm config set cacphe /cache/npm
ENV COMPOSER_HOME=/cache/composer

COPY ./pm4-tools /code/pm4-tools
WORKDIR /code/pm4-tools
RUN composer install --no-interaction

WORKDIR /code
RUN echo "cachebust 1"
COPY build-files/cicd-build-run.sh .